namespace MyMoney.Entities;

public enum ExpenseCategory
{
	NoCategory = 0,
	Auto,
	Charity,
	BudgetAndTaxes,
	CargoTransport,
	Cash,
	MoneyTransfers,
	Investments,
	Other,
	OfficeSupplies,
	CafesAndRestaurants,
	Tickets,
	Cinema,
	Books,
	UtilitiesAndInternet,
	BeautyAndHealth,
	CourierServices,
	ClothesAndFootwear,
	LoanPayment,
	ClothingAndFootwear,
	HouseholdAppliances,
	Travel,
	MobileRecharge,
	GroceriesAndSupermarkets,
	AdvertisingServices,
	Repair,
	EntertainmentAndSports,
	Insurance,
	Taxi,
	Animals,
	FinesAndPenalties,
	Jewelry
}